In [1]:
# TCC: APLICAÇÃO DE MACHINE LEARNING PARA APOSTAS ESPORTIVAS: uso de Regressão Logística,
#      SVM, Árvore de Decisão e Naive Bayes
#
# Aluno: João Henrique
# Orientadora: Renata Alcoforado

In [2]:
# Importando as bases de dados da Itália

import pandas as pd

d1 = pd.read_csv('I1(9).csv')
d2 = pd.read_csv('I1(8).csv')
d3 = pd.read_csv('I1(7).csv')
d4 = pd.read_csv('I1(6).csv')
d5 = pd.read_csv('I1(5).csv')
d6 = pd.read_csv('I1(4).csv')
d7 = pd.read_csv('I1(3).csv')
d8 = pd.read_csv('I1(2).csv')
d9 = pd.read_csv('I1(1).csv')
d10 = pd.read_csv('I1.csv')

# Legenda
#d1 = Dados de 2012/2013
#d2 = Dados de 2013/2014
#d3 = Dados de 2014/2015
#d4 = Dados de 2015/2016
#d5 = Dados de 2016/2017
#d6 = Dados de 2017/2018
#d7 = Dados de 2018/2019
#d8 = Dados de 2019/2020
#d9 = Dados de 2020/2021
#d10 = Dados de 2021/2022

In [3]:
# Criando novas bases de acordo com as variáveis presentes e desejadas para o estudo

bd1 = d1[['Div','Date','HomeTeam','AwayTeam','FTR','B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'VCH', 'VCD', 'VCA', 'WHH', 'WHD', 'WHA']]
bd2 = d2[['Div','Date','HomeTeam','AwayTeam','FTR','B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'VCH', 'VCD', 'VCA', 'WHH', 'WHD', 'WHA']]
bd3 = d3[['Div','Date','HomeTeam','AwayTeam','FTR','B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'VCH', 'VCD', 'VCA', 'WHH', 'WHD', 'WHA']]
bd4 = d4[['Div','Date','HomeTeam','AwayTeam','FTR','B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'VCH', 'VCD', 'VCA', 'WHH', 'WHD', 'WHA']]
bd5 = d5[['Div','Date','HomeTeam','AwayTeam','FTR','B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'VCH', 'VCD', 'VCA', 'WHH', 'WHD', 'WHA']]
bd6 = d6[['Div','Date','HomeTeam','AwayTeam','FTR','B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'VCH', 'VCD', 'VCA', 'WHH', 'WHD', 'WHA']]
bd7 = d7[['Div','Date','HomeTeam','AwayTeam','FTR','B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'VCH', 'VCD', 'VCA', 'WHH', 'WHD', 'WHA']]
bd8 = d8[['Div','Date','HomeTeam','AwayTeam','FTR','B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'VCH', 'VCD', 'VCA', 'WHH', 'WHD', 'WHA']]
bd9 = d9[['Div','Date','HomeTeam','AwayTeam','FTR','B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'VCH', 'VCD', 'VCA', 'WHH', 'WHD', 'WHA']]
bd10 = d10[['Div','Date','HomeTeam','AwayTeam','FTR','B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'VCH', 'VCD', 'VCA', 'WHH', 'WHD', 'WHA']]

In [4]:
# Base de dados das últimas 5 temporadas

dados5anos = pd.concat([bd6,bd7,bd8,bd9,bd10], axis=0, ignore_index=True)
dados5anos.head()

,Div,Date,HomeTeam,AwayTeam,FTR,B365H,B365D,B365A,BWH,BWD,...,IWA,PSH,PSD,PSA,VCH,VCD,VCA,WHH,WHD,WHA
0,I1,19/08/17,Juventus,Cagliari,H,1.14,8.00,19.00,1.16,7.5,...,15.00,1.16,8.29,24.44,1.14,8.0,21.00,1.14,7.50,21.00
1,I1,19/08/17,Verona,Napoli,A,8.00,4.75,1.40,8.00,4.6,...,1.43,8.46,5.08,1.42,7.50,4.8,1.40,8.00,4.50,1.40
2,I1,20/08/17,Atalanta,Roma,A,3.20,3.30,2.30,3.20,3.4,...,2.20,3.17,3.56,2.36,3.20,3.4,2.30,3.10,3.40,2.25
3,I1,20/08/17,Bologna,Torino,D,3.10,3.30,2.38,3.20,3.3,...,2.40,3.29,3.42,2.36,3.25,3.2,2.38,3.10,3.30,2.30
4,I1,20/08/17,Crotone,Milan,A,6.00,4.00,1.57,5.50,4.1,...,1.55,6.04,4.20,1.62,5.50,4.0,1.62,6.00,3.75,1.60

In [5]:
# Exportando o data frame para .csv

dados5anos.to_csv('ITA5anos.csv', index=False)

In [6]:
# Base de dados das últimas 10 temporadas

dados10anos = pd.concat([bd1,bd2,bd3,bd4,bd5,bd6,bd7,bd8,bd9,bd10], axis=0, ignore_index=True)
dados10anos.head()

,Div,Date,HomeTeam,AwayTeam,FTR,B365H,B365D,B365A,BWH,BWD,...,IWA,PSH,PSD,PSA,VCH,VCD,VCA,WHH,WHD,WHA
0,I1,25/08/12,Fiorentina,Udinese,H,2.05,3.2,3.75,2.05,3.30,...,3.40,2.10,3.32,4.13,2.10,3.25,4.00,2.10,3.25,3.60
1,I1,25/08/12,Juventus,Parma,H,1.30,5.0,10.50,1.28,5.00,...,7.30,1.33,5.28,12.27,1.33,5.25,12.00,1.33,4.80,10.00
2,I1,26/08/12,Atalanta,Lazio,A,2.40,3.2,3.00,2.40,3.20,...,2.60,2.47,3.19,3.33,2.45,3.20,3.25,2.50,3.20,2.88
3,I1,26/08/12,Chievo,Bologna,H,2.10,3.2,3.60,2.10,3.15,...,3.20,2.23,3.16,3.92,2.20,3.12,3.90,2.15,3.20,3.60
4,I1,26/08/12,Genoa,Cagliari,H,1.95,3.3,4.00,2.00,3.25,...,3.45,2.03,3.31,4.37,2.05,3.25,4.30,2.10,3.25,3.60

In [7]:
# Exportando o data frame para .csv

dados10anos.to_csv('ITA10anos.csv', index=False)